

  <div class="row">
   <div class="col-lg-12">
    <div style="text-align: center;">
     <h2>Panel zarządu</h2>



           <a class="quick-btn quick-btn-admin" href="<?= base_url('backend/admin_magento_temp');?>">
               <i class="icon-bolt icon-2x"></i>
               <span> Products <br/><-><br/> Magento </span>

               <span class="label <?=$admin_count_magento_temp_class;?>"><?=$admin_count_magento_temp;?></span>
           </a>
           <a class="quick-btn quick-btn-admin" href=" ">
               <i class="icon-bolt icon-2x"></i>
               <span> Magento <br/><-><br/> Products </span>

               <span class="label  "> x </span>
           </a>
           <a class="quick-btn" href="#">
               <i class="icon-bolt icon-2x"></i>
               <span>Komunikaty<br/> &nbsp; <br/> &nbsp;</span>
               <span class="label label-success">x</span>
           </a>
           <a class="quick-btn quick-btn-admin" href="<?= base_url('backend/admin_xml_price_changes');?>">
               <i class="icon-bolt icon-2x"></i>
               <span> XML <br/>Zmiany<br/> Cen </span>

               <span class="label <?=$admin_xml_price_changes_class;?>"><?=$admin_xml_price_changes;?></span>
           </a>
           <a class="quick-btn quick-btn-admin" href="<?= base_url('backend/admin_price_alerts');?>">
               <i class="icon-bolt icon-2x"></i>
               <span> Ceny <br/>ponizej<br/> zakupu </span>

               <span class="label <?=$admin_price_alerts_class;?>"><?=$admin_price_alerts;?></span>
           </a>
       </div>

   </div>



</div>
