<div class="row">
 <div class="col-lg-5">
  <div style="text-align: center;">
   <h2>Produkty ze zmianami cen</h2>
   <table class="table">
     <tr>
       <th>lp #</th>
       <th>SKU</th>
     </tr>
     <?php
     foreach($table as $_table) {
       echo '<tr>';
       echo '<td>';
        echo $_table['lp'];
       echo '</td>';
       echo '<td>';
        echo $_table['sku'];
       echo '</td>';
       echo '</tr>';
     }
     ?>
   </table>
  </div>

 </div>
</div>
