<div id="content">

    <div class="inner" style="min-height: 700px;">
        <div class="row">
            <div class="col-lg-12">
                <h1>Użytkownicy</h1>
            </div>
        </div>

      <div class="row">
        <div class="col-lg-6">
          <h2>Zmiana hasła dla #<?= $id;?></h2>
          <form action="" method="post">

              <div class="form-group">
                  <input type="password" class="form-control" name="password" placeholder="password" value="">
              </div>
              <div class="form-group">
                  <input type="submit" name="passchangeSubmit" class="btn-primary" value="Submit"/>
              </div>
            </form>
        </div>
        <div class="col-lg-6">

        </div>
      </div>
    </div>
  </div>
</div>
