  <div id="content">

      <div class="inner" style="min-height: 700px;">
          <div class="row">
              <div class="col-lg-12">
                  <h1> Allegro </h1>
              </div>
          </div>

        <div class="row">
          <div class="col-lg-3">
                       <div class="panel panel-info">
                            <div class="panel-heading">
                                Synchronizacja
                            </div>

                            <div class="panel-body">
                                <div class="list-group">

                                    <a href="#" class="list-group-item">
                                        <i class="icon-ok"></i> Aktywnych aukcji
                                    <span class="pull-right text-muted small"><em><?=$countActiveAuctions;?></em>
                                    </span>
                                    </a>

                                    <a href="#" class="list-group-item">
                                        <i class=" icon-comment"></i> Ilość komentarzy
                                    <span class="pull-right text-muted small"><em>--</em>
                                    </span>
                                    </a>


                                    <a href="#" class="list-group-item">
                                        <i class="icon-refresh"></i> Ostatnia synchronizacja
                                    <span class="pull-right text-muted small"><em><?=$lastSynchronizationTime;?></em>
                                    </span>
                                    </a>

                                    <a href="#" class="list-group-item">
                                        <i class="icon-refresh"></i> Aktywna sesja:<br/>
                                        <pre>
                                          <?=print_r($_SESSION);?>
                                        </pre>
                                    </a>
                                    <form action="" method="post">
                                      <input name="synchroAllegro" type="submit" class="btn btn-default btn-block btn-primary" value="Pobierz aktualne aukcje">
                                    </form>
                                </div>
                            </div>
                        </div>
                  </div>
                <div class="col-lg-3">
                  <div class="panel panel-info">
                       <div class="panel-heading">
                           Funkcje testowe
                       </div>

                       <div class="panel-body">
                           <div class="list-group">
                               <a href="http://strona_backendu/public/allegro/login/" class="list-group-item">
                                 LoginAPI
                               </a>

                               <a href="http://strona_backendu/public/allegro/categories/" class="list-group-item">
                                 Kategorie
                               </a>

                               <a href="http://strona_backendu/public/allegro/logout/" class="list-group-item">
                                 Logout
                               </a>
                           </div>
                       </div>
                   </div>
                 </div>
                </div>

                <div class="row">
                  <div class="col-lg-6">
                    <div class="panel panel-info">
                      <div class="panel-heading">
                        Obserwowane aukcje
                      </div>
                      <div class="panel-body">
                        <table class="table table-bordered sortableTable responsive-table">
                          <?php
                          foreach($get_obs_auctions as $_get_obs_auctions) {
                            echo '<tr>';
                            echo '<td><i class="icon-ok"></i></td>';
                              echo '<td>'.$_get_obs_auctions->name.'</td>';
                              echo '<td>'.$_get_obs_auctions->sku.'</td>';
                              echo '<td>'.$_get_obs_auctions->allegro_id.'</td>';
                              echo '<td>'.$_get_obs_auctions->last_update.'</td>';
                            echo '</tr>';
                          }
                          ?>
                        </table>

                     </div>
                    </div>
                   </div>

                    <div class="col-lg-6">
                      <div class="panel panel-danger">
                        <div class="panel-heading">
                          Nieobserwowane aukcje
                        </div>
                        <div class="panel-body">
                          <table class="table table-bordered sortableTable responsive-table">
                            <?php
                            foreach($get_not_obs_auctions as $_get_not_obs_auctions) {
                              echo '<tr>';
                              echo '<td><i class="icon-ok"></i></td>';
                                echo '<td>'.$_get_not_obs_auctions->name.'</td>';
                                echo '<td>'.$_get_not_obs_auctions->allegro_id.'</td>';
                                echo '<td>'.$_get_not_obs_auctions->last_update.'</td>';
                              echo '</tr>';
                            }
                            ?>
                          </table>
                       </div>
                      </div>
                     </div>
                    </div>

      </div>
  </div>
</div>
