<!-- FOOTER -->
 <div id="footer">
     <p>all rights reserved &copy;  neptron.pl &nbsp;2011-<?= date('Y');?> &nbsp;</p>
 </div>
 
 <script src="http://strona_backendu/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
 <script src="http://strona_backendu/assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js"></script>
 <script src="http://strona_backendu/assets/plugins/flot/jquery.flot.js"></script>
 <script src="http://strona_backendu/assets/plugins/flot/jquery.flot.resize.js"></script>
 <script src="http://strona_backendu/assets/plugins/flot/jquery.flot.time.js"></script>
 <script src="http://strona_backendu/assets/plugins/flot/jquery.flot.stack.js"></script>
 <script src="http://strona_backendu/assets/js/for_index.js"></script>
 </body>


</html>
