<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->
<head>
  <meta charset="UTF-8" />
  <title>neptron.pl | Backend</title>
  <link rel="icon" href="http://strona_backendu/assets/img/favicon.ico" type="image/x-icon"/>
  <link rel="shortcut icon" href="http://strona_backendu/assets/img/favicon.ico" type="image/x-icon"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
     <link rel="stylesheet" href="http://strona_backendu/assets/plugins/bootstrap/css/bootstrap.css" />
     <link rel="stylesheet" href="http://strona_backendu/assets/css/main.css" />
     <link rel="stylesheet" href="http://strona_backendu/assets/css/theme.css" />

     <link rel="stylesheet" href="http://strona_backendu/assets/css/MoneAdmin.css" />
     <link rel="stylesheet" href="http://strona_backendu/assets/plugins/Font-Awesome/css/font-awesome.css" />

</head>
<script src="http://strona_backendu/assets/plugins/jquery-2.0.3.min.js"></script>
