

  <div class="row">
   <div class="col-lg-5">
    <div style="text-align: center;">
     <h2>Twoje konto</h2>

           <!--

           <a class="quick-btn" href="#">
               <i class="icon-envelope icon-2x"></i>
               <span>Messages</span>
               <span class="label label-success">456</span>
           </a>
-->
           <a class="quick-btn" href="#">
               <i class="icon-signal icon-2x"></i>
               <span>Obroty</span>
               <span class="label label-default">0zł</span>
           </a>

           <a class="quick-btn" href="#">
               <i class="icon-bolt icon-2x"></i>
               <span>Komunikaty</span>
               <span class="label label-default">0</span>
           </a>
<!--

-->
       </div>

   </div>
   <div class="col-lg-5">
    <div style="text-align: center;">
     <h2>neptron ERP</h2>
     <a class="quick-btn" href="<?= base_url('products/overview/');?>">
      <i class="icon-check icon-2x"></i>
      <span>Produkty</span>
      <span class="label label-info"><?= $count_products?></span>
     </a>
    </div>
   </div>


</div>
